### ISSUE TITLE
Preserve file attributes while copying with 'extra-resource' option

### ISSUE THREAD

**Issue by ma-sattari** [electron/packager#1523]
### Preflight Checklist

* [X] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/main/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

According to file [usage.txt](https://github.com/electron/electron-packager/blob/main/usage.txt) when using `extra-resource` option in build time you use `fs-extra` package to copy extra resources to `target` folder. However, the attributes of file is cleared after copy operation is done. We have an executable C file with (rwx rwx r--) bits set. When file is copied to target directory executable attribute of file is removed and we are not able to execute it within electron.

### Proposed Solution

According to this file from [Copy Usage](https://github.com/jprichardson/node-fs-extra/blob/master/docs/copy.md) `fs-extra` package you may pass a `preserveTimestamps` `<boolean>` option when calling `copy` function like this: _copy(src, dest[, options][, callback])_.
According to this code snippet [copy.js](https://github.com/jprichardson/node-fs-extra/blob/cc7b3b22a984de5124131c7897574091c9df00e1/lib/copy/copy.js#L106) when using this option we may preserve `mode` in addition to `Timestamps`.  Updating this code in your repo [platform.js](https://github.com/electron/electron-packager/blob/036b954d47701192063cb352ed1580f4adfd5487/src/platform.js#L250) and adding the `preserveTimestamps`  option will add the capability to preserve both  `Timestamps` and `mode` in the target directory.

**Comment by yangannyx** [comment]
Hello! Are you still running into this issue @ma-sattari? Looking at this [line](https://github.com/jprichardson/node-fs-extra/blob/cc7b3b22a984de5124131c7897574091c9df00e1/lib/copy/copy.js#L102) in fs-extra's copy.js, it seems like the destination file is always set to the same `mode` as the source file.
