### ISSUE TITLE
packagerConfig.afterAsar hook causes long build waits

### ISSUE THREAD

**Issue by nijinekoyo** [electron/packager#1729]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/packager/blob/main/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
```
Electron Packager 18.3.2
Node v20.5.1
Host Operating system: win32 10.0.22631 (x64)
```
* **Electron Version:**
```
v30.0.9
```
* **Operating System:**
```
Windows 11 (23H2)
```

### Expected Behavior
Build normally and print information

### Actual Behavior
After adding afterAsar hook to config file, build waits infinitely at `Packaging application.Packaging for x64 on win32.Finalizing package` phase
```
> yarn package
yarn run v1.22.22
$ electron-forge package
✔ Checking your system
✔ Preparing to package application
✔ Running packaging hooks
  ✔ Running generateAssets hook
  ✔ Running prePackage hook
❯ Packaging application
  › Determining targets...
  ❯ Packaging for x64 on win32
    ✔ Copying files
    ✔ Preparing native dependencies [3s]
    ⠇ Finalizing package
◼ Running postPackage hook
```

### Additional Information
CODE: 
``` js
export const packagerConfig = {
  asar: true,
  ignore: [
    "node_modules/",
    ".gitignore",
    "forge.config.js",
    "yarn.lock",
  ],
  afterAsar: [
    async (buildPath, electronVersion, platform, arch) => {
      console.log('after asar', buildPath, electronVersion, platform, arch);
      return;
    },
  ],
};
```

**Comment by MarshallOfSound** [comment]
Electron packager hook functions are not promises (unfortunately) they still use old callback systems 🙃 

https://electron.github.io/packager/main/types/HookFunction.html

If you want a promise based hooks API you should use the forge-level [`packageX`](https://www.electronforge.io/config/hooks#packageaftercopy) hooks.

But changing your code to this should fix the hang you're seeing
```js
export const packagerConfig = {
  asar: true,
  ignore: [
    "node_modules/",
    ".gitignore",
    "forge.config.js",
    "yarn.lock",
  ],
  afterAsar: [
    (buildPath, electronVersion, platform, arch, cb) => {
      console.log('after asar', buildPath, electronVersion, platform, arch);
      return cb();
    },
  ],
};
```

**Comment by nijinekoyo** [comment]
That's right, thank you very much
